spring.application.name=rag-chat-management-service

management.endpoints.web.exposure.include=health

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format-sql=true
spring.jpa.database=mysql
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.show-sql=true
spring.jpa.hibernate.ddl-auto=update

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

app.api.key=${API_AUTH_KEY}

spring.config.import=optional:file:.env[.properties]

